# Generated by Django 5.2.6 on 2025-09-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('area', '0003_alter_city_options_alter_state_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={},
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('state', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('country', 'name')},
        ),
    ]
